name: Generate Datas

on:
  schedule:
    # Executa a cada 12 horas (às 00:00 e 12:00 UTC)
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar SVG da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: jeanr0cha
          svg_out_path: github-contribution-grid-snake.svg

      - name: Publicar na branch output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
